# Generated by Django 4.0.2 on 2022-02-10 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
