# Generated by Django 4.0.2 on 2022-02-12 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_banner_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='votes',
            field=models.ManyToManyField(blank=True, null=True, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
