# Generated by Django 4.0.2 on 2022-02-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_image_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='limit',
            field=models.IntegerField(default=0),
        ),
    ]
